sudo: required

language: python
python:
  - 3.6

matrix:
  include:
    - compiler: gcc
      before_script:
        - python3 -m pip install numpy sphinx
      script:
        - ./configure
        - make install
        - make check
        - git clean -xdf
        - python3 setup.py develop
        - python3 setup.py test
        - python3 setup.py doctest
        - git clean -xdf
        - python3 setup.py install
        - python3 setup.py test
        - python3 setup.py doctest

    - compiler: clang
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y valgrind
        - python3 -m pip install numpy sphinx
      script:
        - ./configure
        - make install
        - make memcheck
        - git clean -xdf
        - python3 setup.py develop
        - python3 setup.py test
        - python3 setup.py doctest
        - git clean -xdf
        - python3 setup.py install
        - python3 setup.py test
        - python3 setup.py doctest

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
      before_script:
        - export CC=clang
      script:
        - ./configure
        - make install
        - make check
        - git clean -xdf
        - python3 setup.py develop
        - python3 setup.py test
        - git clean -xdf
        - python3 setup.py install
        - python3 setup.py test

    - compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        - bash Miniconda3-latest-Linux-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - conda update --yes conda
        - conda install --yes conda-build=3.3.0
        - conda install --yes anaconda-client
      script:
        - cd xnd-all
        - git fetch --unshallow
        - cd scripts
        - ./conda-install.sh
        - export LIBNDTYPES=`conda build --output build/ndtypes/.conda/libndtypes`
        - export NDTYPES=`conda build --output build/ndtypes/.conda/ndtypes`
        - export LIBXND=`conda build --output build/xnd/.conda/libxnd`
        - export XND=`conda build --output build/xnd/.conda/xnd`
        - export LIBGUMATH=`conda build --output build/gumath/.conda/libgumath`
        - export GUMATH=`conda build --output build/gumath/.conda/gumath`
