sudo: required

language: python
python:
  - 3.6

matrix:
  include:
    - compiler: gcc
      script:
        - ./configure
        - make install
        - make check

    - compiler: clang
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y valgrind
      script:
        - ./configure
        - make install
        - make memcheck

    - compiler: gcc
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y python3-numpy
      script:
        - python3 setup.py develop
        - python3 setup.py test

    - compiler: gcc
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y python3-numpy
      script:
        - python3 setup.py install
        - python3 setup.py test

    - compiler: gcc
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y python3-sphinx
      script:
        - python3 setup.py develop
        - python3 setup.py doctest

    - compiler: gcc
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y python3-sphinx
      script:
        - python3 setup.py install
        - python3 setup.py doctest

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
      before_script:
        - export CC=clang
      script:
        - ./configure
        - make install
        - make check

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
        - brew install numpy --with-python3
      before_script:
        - export CC=clang
      script:
        - python3 setup.py develop
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
        - brew install numpy --with-python3
      before_script:
        - export CC=clang
      script:
        - python3 setup.py install
        - python3 setup.py test
