skip_tags: true

matrix:
  fast_finish: true

os: Visual Studio 2015

build_script:
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe" C:\Miniconda.exe
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - set PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda update --yes conda
  - conda install --yes conda-build=3.3.0
  - conda install --yes anaconda-client
  - conda install --yes numpy
  - conda install --yes numba
  - conda install --yes ndtypes -c xnd/label/dev
  - conda install --yes xnd -c xnd/label/dev
  - conda-build .conda/libgumath -c xnd/label/dev
  - conda-build .conda/gumath -c xnd/label/dev
  - ps: $env:LIBGUMATH = (conda build --output .conda/libgumath -c xnd/label/dev)
  - ps: $env:GUMATH = (conda build --output .conda/gumath -c xnd/label/dev)

on_success:
  - ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { cmd /C anaconda --token $env:anaconda_token upload $env:LIBGUMATH --user xnd --label dev "2>&1" }
  - ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { cmd /C anaconda --token $env:anaconda_token upload $env:GUMATH --user xnd --label dev "2>&1" }

environment:
  anaconda_token:
    secure: rTnsCbMjHi/mOYo8Tz2SzaungqlrdypPkMMzuMniN06Gv2fgCizppeKw2gz/kQ7T
