skip_tags: true

image: Visual Studio 2017

environment:
  matrix:
    - PLATFORM: "x64"
      PYTHON: "C:\\Python37-x64"
    - PLATFORM: "x86"
      PYTHON: "C:\\Python37"

install:
  - "%PYTHON%\\python.exe -m pip install numpy"

build_script:
  - git clone https://github.com/plures/ndtypes.git
  - git clone https://github.com/plures/xnd.git
  - cd ndtypes
  - "%PYTHON%\\python.exe setup.py install --local=\"%cd%\\..\\python\""
  - cd ..\xnd
  - "%PYTHON%\\python.exe setup.py install --local=\"%cd%\\..\\python\""
  - cd ..
  - "%PYTHON%\\python.exe setup.py build"
  - "%PYTHON%\\python.exe setup.py test"

