sudo: required

language: python
python:
  - 3.6

matrix:
  include:
    - compiler: gcc
      before_script:
        - python3 -m pip install numpy sphinx
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test
        - python3 setup.py doctest

    - compiler: gcc
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y valgrind
      script:
        - ./configure --with-valgrind
        - make parser
        - make memcheck
        - python3 setup.py module
        - python3 setup.py test

    - compiler: clang
      before_script:
        - export CC=clang
      script:
        - ./configure
        - make parser
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
      before_script:
        - export CC=clang
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - compiler: gcc
      script:
        - python3 setup.py build
        - python3 setup.py test
