package:
  name: xndtools
  version: 0.2.0dev3

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY', 'NA') }}_{{ environ.get('GIT_BUILD_STR', 'NA') }}

test:
  files:
    - test
  commands:
    - xnd_tools --helpl

requirements:
  build:
    - libndtypes ==0.2.0dev3
    - libxnd ==0.2.0dev3
    - libgumath ==0.2.0dev3
    - ndtypes ==0.2.0dev3
    - xnd ==0.2.0dev3
  run:
    - libndtypes ==0.2.0dev3
    - libxnd ==0.2.0dev3
    - libgumath ==0.2.0dev3
    - ndtypes ==0.2.0dev3
    - xnd ==0.2.0dev3

about:
  home: https://github.com/plures/xndtools
  license: BSD 3-clause
