sudo: required

language: python
python:
  - 3.6

matrix:
  include:
    - compiler: gcc
      before_script:
        - python3 -m pip install numpy sphinx
        - git clone https://github.com/plures/ndtypes.git
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test
        - python3 setup.py doctest

    - compiler: gcc
      before_script:
        - sudo apt-get install -y valgrind
        - git clone https://github.com/plures/ndtypes.git
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make memcheck
        - python3 setup.py module
        - python3 setup.py test

    - compiler: clang
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=clang
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=clang
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - compiler: gcc
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - python3 setup.py build
        - python3 setup.py test
